import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { useMemo } from "react";
import { Text, View } from "react-native";
import { AgapButton } from "../components/common/AgapButton";
import { AgapCard } from "../components/common/AgapCard";
import { AgapHeader } from "../components/common/AgapHeader";
import { EmptyState } from "../components/common/EmptyState";
import { ErrorState } from "../components/common/ErrorState";
import { LoadingState } from "../components/common/LoadingState";
import { ScreenContainer } from "../components/common/ScreenContainer";
import { RecommendationList } from "../components/session/RecommendationList";
import { useDashboard } from "../hooks/useDashboard";
import { useSessionDetail } from "../hooks/useSessionDetail";
import type { RootStackParamList } from "../navigation/types";
import { useAppStore } from "../store/appStore";

type Nav = NativeStackNavigationProp<RootStackParamList>;

export function CoachScreen() {
  const navigation = useNavigation<Nav>();
  const { selectedSessionId } = useAppStore();
  const { dashboard, isLoading, error, refresh } = useDashboard();

  const sessionIdForCoach = useMemo(() => {
    return selectedSessionId ?? dashboard?.latest_highlights[0]?.session_id ?? null;
  }, [dashboard?.latest_highlights, selectedSessionId]);

  const {
    session,
    isLoading: isSessionLoading,
    error: sessionError,
    refresh: refreshSession,
  } = useSessionDetail(sessionIdForCoach);

  if (isLoading) {
    return (
      <ScreenContainer>
        <AgapHeader
          title="Coach"
          subtitle="Backend-grounded coaching overview"
          rightLabel="Coach"
        />
        <LoadingState label="Loading coaching context..." />
      </ScreenContainer>
    );
  }

  if (error) {
    return (
      <ScreenContainer>
        <AgapHeader
          title="Coach"
          subtitle="Backend-grounded coaching overview"
          rightLabel="Coach"
        />
        <ErrorState message={error.message} onRetry={() => void refresh()} />
      </ScreenContainer>
    );
  }

  if (!dashboard) {
    return (
      <ScreenContainer>
        <AgapHeader
          title="Coach"
          subtitle="Backend-grounded coaching overview"
          rightLabel="Coach"
        />
        <EmptyState
          title="No coaching context yet"
          description="Sync at least one session and coaching context will appear here."
          actionLabel="Open History"
          onAction={() =>
            navigation.navigate("MainTabs", { screen: "SessionHistory" })
          }
        />
      </ScreenContainer>
    );
  }

  return (
    <ScreenContainer scrollable>
      <AgapHeader
        title="Coach"
        subtitle="Backend-grounded coaching overview"
        rightLabel="Coach"
      />

      <AgapCard>
        <Text className="text-[11px] uppercase tracking-[1px] text-[#8FAAD2]">
          Active Context
        </Text>
        <Text className="mt-2 text-base font-semibold text-[#EEF4FF]">
          Session {sessionIdForCoach ?? "Unavailable"}
        </Text>
        <Text className="mt-2 text-sm leading-6 text-[#A8C0E5]">
          This screen only displays recommendations and pre-analysis generated by
          backend session processing.
        </Text>
      </AgapCard>

      {isSessionLoading ? (
        <View className="mt-4">
          <LoadingState label="Loading selected session coaching payload..." />
        </View>
      ) : null}

      {!isSessionLoading && sessionError ? (
        <View className="mt-4">
          <ErrorState
            message={sessionError.message}
            onRetry={() => void refreshSession()}
          />
        </View>
      ) : null}

      {!isSessionLoading && !sessionError && session ? (
        <>
          <AgapCard className="mt-4">
            <Text className="text-[11px] uppercase tracking-[1px] text-[#8EA8CF]">
              Pre-Analysis Summary
            </Text>
            <Text className="mt-2 text-sm leading-6 text-[#D8E7FF]">
              {session.latestPreAnalysis?.summary ??
                "No pre-analysis summary available for this session yet."}
            </Text>
          </AgapCard>

          <View className="mt-4">
            <RecommendationList
              title="Session Recommendations"
              items={session.latestDeviceResponse?.recommendations ?? []}
              emptyMessage="No recommendations returned by backend for this session yet."
            />
          </View>
        </>
      ) : null}

      <AgapCard className="mt-4">
        <Text className="text-xs leading-6 text-[#A8C0E5]">
          Coach guidance is informational and not a medical diagnosis.
        </Text>
      </AgapCard>

      <View className="mt-4 gap-3">
        <AgapButton
          title="Open Insight Chat"
          onPress={() => navigation.navigate("MainTabs", { screen: "InsightChat" })}
        />
        <AgapButton
          title="Run Advanced Analysis"
          variant="secondary"
          onPress={() => {
            if (sessionIdForCoach) {
              navigation.navigate("AdvancedAnalysisInput", {
                sessionId: sessionIdForCoach,
              });
              return;
            }

            navigation.navigate("MainTabs", { screen: "SessionHistory" });
          }}
        />
      </View>
    </ScreenContainer>
  );
}
